package main

import (
	"WB1/tasks"
	"WB1/verbal"
	"fmt"
)

func main() {
	fmt.Println("Задание 1")
	tasks.Task1()
	fmt.Println("Задание 2")
	tasks.Task2()
	fmt.Println("Задание 3")
	tasks.Task3()
	fmt.Println("Задание 4")
	tasks.Task4()
	fmt.Println("Задание 5")
	tasks.Task5()
	fmt.Println("Задание 6")
	tasks.Task6()
	fmt.Println("Задание 7")
	tasks.Task7()
	fmt.Println("Задание 8")
	tasks.Task8()
	fmt.Println("Задание 9")
	tasks.Task9()
	fmt.Println("Задание 10")
	tasks.Task10()
	fmt.Println("Задание 11")
	tasks.Task11()
	fmt.Println("Задание 12")
	tasks.Task12()
	fmt.Println("Задание 13")
	tasks.Task13()
	fmt.Println("Задание 14")
	tasks.Task14()
	fmt.Println("Задание 15")
	tasks.Task15()
	fmt.Println("Задание 16")
	tasks.Task16()
	fmt.Println("Задание 17")
	tasks.Task17()
	fmt.Println("Задание 18")
	tasks.Task18()
	fmt.Println("Задание 19")
	tasks.Task19()
	fmt.Println("Задание 20")
	tasks.Task20()
	fmt.Println("Задание 21")
	tasks.Task21()
	fmt.Println("Задание 22")
	tasks.Task22()
	fmt.Println("Задание 23")
	tasks.Task23()
	fmt.Println("Задание 24")
	tasks.Task24()
	fmt.Println("Задание 25")
	tasks.Task25()
	fmt.Println("Задание 26")
	tasks.Task26()
	fmt.Println("Устное Задание 1")
	verbal.Task1()
	fmt.Println("Устное Задание 2")
	verbal.Task2()
	fmt.Println("Устное Задание 3")
	verbal.Task3()
	fmt.Println("Устное Задание 4")
	verbal.Task4()
	fmt.Println("Устное Задание 5")
	verbal.Task5()
	fmt.Println("Устное Задание 6")
	verbal.Task6()
	fmt.Println("Устное Задание 7")
	verbal.Task7()
	fmt.Println("Устное Задание 8")
	verbal.Task8()
	fmt.Println("Устное Задание 9")
	verbal.Task9()
	fmt.Println("Устное Задание 10")
	verbal.Task10()
	fmt.Println("Устное Задание 11")
	verbal.Task11()
	fmt.Println("Устное Задание 12")
	verbal.Task12()
	fmt.Println("Устное Задание 13")
	verbal.Task13()
	fmt.Println("Устное Задание 14")
	verbal.Task14()
}
